### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by jginesclavero** [IntelligentRoboticsLabs/BICA#7]
CMake Error at BICA/bica_examples/CMakeLists.txt:123 (add_executable):
  Cannot find source file:
   src/planning/planning_example_elements_node.cpp

**Comment by jginesclavero** [comment]
Comento la compilacion de ese nodo en CMakeList y lo subo como parche temporal.

**Comment by bekirbostanci** [comment]
how did you solve the problem I have a same problem can you help me @jginesclavero
